第五十一节，异常处理和断言

**try关键字，定义获取程序错误1**

**except关键字，出现异常错误执行里面的代码2**

**Exception定义错误类， **Exception能获取到所有类型的错误错误， **as创建错误对象名称，自动获取错误信息3******

    
    
     #!/usr/bin/env python
    # -*- coding:utf8 -*-
    """获取程序错误信息"""
    try: #try关键字定义获取程序错误
        #代码块
        a = str(字符串)
        print(a)
    except Exception as e: #except关键字出现异常错误执行里面的代码，Exception定义错误类，as创建错误对象自动获取错误信息
        print(e) #打印错误对象输出错误信息
    # 输出
    # name '字符串' is not defined



**python中的异常种类非常多，每个异常专门用于处理获取某一项异常4**

**常见错误类型5**

    
    
    AttributeError 试图访问一个对象没有的树形，比如foo.x，但是foo没有属性x
    IOError 输入/输出异常；基本上是无法打开文件
    ImportError 无法引入模块或包；基本上是路径问题或名称错误
    IndentationError 语法错误（的子类） ；代码没有正确对齐
    IndexError 下标索引超出序列边界，比如当x只有三个元素，却试图访问x[5]
    KeyError 试图访问字典里不存在的键
    KeyboardInterrupt Ctrl+C被按下
    NameError 使用一个还未被赋予对象的变量
    SyntaxError Python代码非法，代码不能编译(个人认为这是语法错误，写错了）
    TypeError 传入对象类型与要求的不符合
    UnboundLocalError 试图访问一个还未被设置的局部变量，基本上是由于另有一个同名的全局变量，
    导致你以为正在访问它
    ValueError 传入一个调用者不期望的值，即使值的类型是正确的  
      
     **更多错误类型6  
    **
    
    
    ArithmeticError
    AssertionError
    AttributeError
    BaseException
    BufferError
    BytesWarning
    DeprecationWarning
    EnvironmentError
    EOFError
    **Exception   能获取所有类型错误，其他的错误类型只能获取对应的错误**
    FloatingPointError
    FutureWarning
    GeneratorExit
    ImportError
    ImportWarning
    IndentationError
    IndexError
    IOError
    KeyboardInterrupt
    KeyError
    LookupError
    MemoryError
    NameError
    NotImplementedError
    OSError
    OverflowError
    PendingDeprecationWarning
    ReferenceError
    RuntimeError
    RuntimeWarning
    StandardError
    StopIteration
    SyntaxError
    SyntaxWarning
    SystemError
    SystemExit
    TabError
    TypeError
    UnboundLocalError
    UnicodeDecodeError
    UnicodeEncodeError
    UnicodeError
    UnicodeTranslateError
    UnicodeWarning
    UserWarning
    ValueError
    Warning
    ZeroDivisionError
    
    
    **  
    我们在以后记录错误时，要想记录对应的错误信息可以用以下办法7    
    先用对应的错误类型来获取，如果都不是前面对应的错误类型，最后用 **Exception来获取  
    ****
    
    
     #!/usr/bin/env python
    # -*- coding:utf8 -*-
    """获取程序错误信息"""
    try:
        a = str(字符串)
        print(a)
    except AttributeError as c: #出现对应错误就获取到信息，打印出来，如果不是对应错误则不执行
        print(c)
    except IOError as d: #出现对应错误就获取到信息，打印出来，如果不是对应错误则不执行
        print(d)
    except ImportError as e: #出现对应错误就获取到信息，打印出来，如果不是对应错误则不执行
        print(e)
    except Exception as f: #都不是上面对应的错误，用Exception来不管是上面错误都获取到
        print(f)
    # 输出
    # name '字符串' is not defined

**完整异常处理代码块8**

**else主代码块执行完，执行该块9**  
 **finally无论异常与否，最终执行该块10**

    
    
     #!/usr/bin/env python
    # -*- coding:utf8 -*-
    try:
        #主代码块
        a = str(hjhb)
    except Exception as e:
        #代码错误执行模块
        print(e)
    else:
        print("主代码块执行完，执行该块")
    finally:
        print("无论异常与否，最终执行该块")



**主动触发异常，也就是没有错误，主动触发一个错误11**

**raise关键字， **主动触发一个错误12****

    
    
     #!/usr/bin/env python
    # -*- coding:utf8 -*-
    try:
        #主代码块
        a = str("1234")
        raise Exception('错误了。。。')
    except Exception as e:
        #代码错误执行模块
        print(e)
    # 输出
    # 错误了。。。



**断言13**

**assert 条件，条件成立就成立继续执行，条件不成立就报错，一般用于测试14**

    
    
     #!/usr/bin/env python
    # -*- coding:utf8 -*-
    assert 1 == 1
    print("123")
    assert 1 == 2
    print("456")









    
    
    **** ****



